config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get '/profile', to: 'pages#profil'
  resources :starships do
    resources :rentals, only: %i[new create]
  end

  # Define a route to access rentals index and show page and destroy a rental
  # resources :rentals, only: %i[index show destroy]

  # Define a collection of route that show bookings from the point of view of renter and reservations from the point of view of loaner
  resources :rentals do
    resources :reviews, only: %i[new create]
    collection do
      get :bookings
      get :requests
    end
    member do
      get :accept
      get :decline
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :renter, class_name: 'User'
  belongs_to :starship
  has_one :review, dependent: :destroy
  validates :start_date, presence: true, format: {
    with: /\A\d{4}-\d{2}-\d{2}\z/, message: "must be in the format YYYY-MM-DD"
  }
  validates :end_date, presence: true, format: {
    with: /\A\d{4}-\d{2}-\d{2}\z/, message: "must be in the format YYYY-MM-DD"
  }
  validates :price, presence: true

  delegate :loaner, to: :starship
  validates :status, presence: true
  # status is an enum that can be either pending, accepted or declined,
  # it is set to pending by default in the database
  enum status: { pending: 0, accepted: 1, declined: 2 }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :rental
  # belongs_to :user, through: :rental
  # belongs_to :starship, through: :rental
  validates :rating, presence: true, numericality: {
    only_integer: true, greater_than_or_equal_to: 1,
    less_than_or_equal_to: 5
  }
  validates :content, presence: true
end

app/models/starship.rb
class Starship < ApplicationRecord
  belongs_to :loaner, class_name: 'User'
  has_many :rentals, dependent: :destroy
  has_many :renters, through: :rentals
  has_many :reviews, through: :rentals
  has_many_attached :photos

  validates :name, presence: true
  validates :description, presence: true
  validates :price_per_day, numericality: { only_numeric: true }, presence: true

  geocoded_by :pickup_city
  after_validation :geocode, if: :will_save_change_to_pickup_city?

  def average_rate
    sum = 0
    rentals.each do |rental|
      sum += rental.review.rating
    end
    (sum.to_f / rentals.length).round(1)
  end

  def attach_photos
    return if photos.blank?

    @starship.attach(photos)
    self.new_photos = []
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  has_many :rentals
  has_many :reviews, through: :rentals
  has_many :starships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  def owner?
    Starship.where(loaner: self).length >= 1
  end

  def owner_of?(starship)
    self == Starship.find(starship.id).loaner
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end

  def profile; end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: %i[show edit update destroy accept decline]

  # Index only shows rentals for the current user

  def bookings
    @rentals = Rental.where(renter: current_user)
  end

  def requests
    @rentals = Rental.joins(:starship).where(starship: { loaner_id: current_user.id })
  end

  def new
    @rental = Rental.new
    @starship = Starship.find(params[:starship_id])
  end

  def create
    @rental = Rental.new(rental_params)
    @rental.renter_id = current_user.id
    @rental.starship_id = params[:starship_id]
    # rental price is calculated by multiplying the price per day of the starship
    # by the number of days and is at minimum equal to the price per day
    @rental.price = [@rental.starship.price_per_day * (@rental.end_date - @rental.start_date).to_i, @rental.starship.price_per_day].max
    if @rental.save
      redirect_to bookings_rentals_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @rental.update(rental_params)
      redirect_to bookings_rentals_path(@rental)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @rental.destroy
    redirect_to bookings_rentals_path, notice: 'Rental was successfully canceled.'
    flash[:notice] = "Rental was successfully canceled."
  end

  def show
  end

  # This method is called when the user clicks on the "Accept" button on the rental
  # The rental ID is passed as a parameter
  # It changes the status of the rental to "accepted"
  def accept
    @rental.status = :accepted
    @rental.save
    redirect_to bookings_rentals_path(@rental), notice: 'Booking accepted.'
    flash[:notice] = "Booking accepted."
  end

  # This method is called when the user clicks on the "Decline" button on the rental
  # The rental ID is passed as a parameter
  # It changes the status of the rental to "declined"
  def decline
    @rental.status = :declined
    @rental.save
    redirect_to bookings_rentals_path(@rental), notice: 'Booking declined.'
    flash[:notice] = "Booking declined."
  end

  private

  def set_rental
    @rental = Rental.find(params[:id])
  end

  def rental_params
    params.require(:rental).permit(:start_date, :end_date, :starship_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_rental, only: %i[new create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.rental = @rental
    if @review.save!
      redirect_to bookings_rentals_path, notice: "Review created. Thank you!"
      flash[:notice] = "Review created. Thank you!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_rental
    @rental = Rental.find(params[:rental_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating, :rental_id)
  end
end

app/controllers/starships_controller.rb
class StarshipsController < ApplicationController
  before_action :set_starship, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @starships = Starship.all
    @markers = @starships.geocoded.map do |starship|
      starship_marker(starship)
    end
  end

  def new
    @starship = Starship.new
  end

  def create
    @starship = Starship.new(starship_params)
    @starship.loaner_id = current_user.id
    if @starship.save
      redirect_to starship_path(@starship)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @markers = [starship_marker(@starship)]
  end

  def edit
  end

  def update
    if @starship.update(starship_params)
      redirect_to starship_path(@starship)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @starship.destroy
    redirect_to starships_path, status: :see_other
  end

  private

  def set_starship
    @starship = Starship.find(params[:id])
  end

  def starship_params
    params.require(:starship).permit(:name, :description, :pickup_city, :price_per_day, photos: [])
  end

  def starship_marker(starship)
    {
      lat: starship.latitude,
      lng: starship.longitude,
      info_window_html: render_to_string(partial: "info_window", locals: {starship: starship}),
      marker_html: render_to_string(partial: "marker")
    }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookAStarship</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <div class="main-container-app">
      <%= render "shared/navbar" %>
      <%= yield %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
  </body>
</html>

app/views/pages/_profil-navbar.erb
<%= link_to edit_user_registration_path do %>
  <div class="profil-card">
    <h3>Editer mon profil</h3>
  </div>
<% end %>

app/views/pages/home.html.erb
<div class=" background-image">
    <div class="second-container">
      <h1> Find the perfect starship for your travel ! </h1>
      <%= link_to "See all starships", starships_path, class: "btn btn-primary"%>
    </div>
</div>

app/views/pages/profil.html.erb
<div class="profil-container">
  <div class="profil-info">
  <h2>Bonjour <%= current_user.first_name %></h2>
  </div>
  <div class="profil-navbar">
    <%= render 'profil-navbar' %>
  </div>
</div>

app/views/rentals/bookings.html.erb
<div class="card-rental-header">
  <h2 style="text-align: center;">My Bookings</h2>
</div>
<% if flash[:notice] %>
  <script>
    alert("<%= j flash[:notice] %>");
  </script>
<% end %>
<div class="row justify-content-center">
  <% @rentals.each do |rental| %>
    <%# display only the rentals for the current user if there is any bookings%>
    <% if rental.renter_id == current_user.id %>
      <div class="row rental card-rental-card">
        <div class="col-sm-3 card-rental-photo">
          <% rental.starship.photos.each do |photo|%>
            <%= cl_image_tag photo.key, height: 200, width:250, crop: :fill %>
          <%end%>
        </div>
        <div class="col-sm-9 card-rental-info">
          <div class="row">
            <div class="col-sm-10">
              <h3><%= rental.starship.name %></h3>
            </div>
            <div class="col-sm-2 card-rental-status">
              <%= rental.status %>
            </div>
          </div>
          <p><%= rental.starship.description %></p>
          <p>Start:<%= rental.start_date %></p>
          <p>End: <%= rental.end_date %></p>
          <p>Owner: <%= rental.loaner.last_name %> <%= rental.loaner.first_name %></p>
          <p>Total price: CHF <%= rental.price %>.-</p>
          <%# if rental status is pending, display Cancel booking%>
          <% if rental.status == "pending" %>
            <%= link_to "Cancel booking", rental_path(rental), data: { "turbo-method": :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-primary" %>
          <% end %>
          <% if rental.review.blank? && rental.status == "accepted" %>
            <button type="button" class="btn btn-primary"><%= link_to "Write a review", new_rental_review_path(rental)%></button>
          <% end %>
        </div>
      </div>
    <% else %>
      <p>You have no bookings</p>
    <% end %>
  <% end %>
</div>
</div>
</div>

app/views/rentals/edit.html.erb
<h2>Edit rental</h2>

app/views/rentals/index.html.erb
<div class="card-rental-header">
  <h2 style="text-align: center;">My Bookings</h2>
</div>

<% if flash[:notice] %>
  <script>
    alert("<%= j flash[:notice] %>");
  </script>
<% end %>

<div class="row justify-content-center">
  <% @rentals.each do |rental| %>
  <%# display only the rentals for the current user%>
  <% if rental.renter_id == current_user.id %>
    <div class="row rental card-rental-card">
      <div class="col-sm-3 card-rental-photo">
        <% rental.starship.photos.each do |photo|%>
          <%= cl_image_tag photo.key, height: 200, width:250, crop: :fill %>
  <%end%>
      </div>

      <div class="col-sm-9 card-rental-info">
        <h3><%= rental.starship.name %></h3>
        <p><%= rental.starship.description %></p>
        <p>Start:<%= rental.start_date %></p>
        <p>End: <%= rental.end_date %></p>
        <p>Owner: <%= rental.loaner.last_name %> <%= rental.loaner.first_name %></p>
        <p>Total price: CHF <%= rental.price %>.-</p>
        <button type="button" class="btn btn-primary">Cancel booking</button>
        <button type="button" class="btn btn-primary">Write a review</button>
      </div>


      <%# display Accept and Decline buttons if rental.pending?%>
      <%# if rental.pending? %>
        <%#= link_to 'Accept', accept_rental_path(rental), method: :patch %>
        <%#= link_to 'Decline', decline_rental_path(rental), method: :patch %>
      <%# end %>
      <%# display Delete only if the current user is the loaner%>
      <%# if rental.starship.loaner_id == current_user.id %>
        <%#= link_to 'Delete', rental_path(rental), method: :delete %>
      <%# end %>
    </div>
    <% else %>
      <p>You have no rentals</p>
    <% end %>
  <% end %>
  </div>
  </div>
</div>

app/views/rentals/new.html.erb
<%# This is the form for creating a new rental %>
<%# create a new rental by selecting a start date and end date in the format YYYY-MM_DD%>
<%# the start_date can't be prior to today%>
<%# the end_date can't be prior to the start_date%>
<div class="form-container d-flex flex-column text-center rounded">
  <h4>Rent the <%= @starship.name %></h4>
  <% @starship.photos.each do |photo| %>
    <%= cl_image_tag photo.key, class:"img rounded mb-3" %>
  <% end %>
  <div class="form-control bg-white" data-controller='rental' data-rental-price-per-day-value="<%= @starship.price_per_day %>">
    <%= simple_form_for [@starship, @rental] do |f| %>
      <div class="form-label rounded">
        <%= f.label :start_date %><br>
        <%= f.date_field :start_date, min: Date.today, data: { action: "change->rental#calculateSum", "rental-target": "startDate" } %>
      </div>
      <div class="field mb-2 rounded">
        <%= f.label :end_date %><br>
        <%= f.date_field :end_date, min: Date.tomorrow, data: { action: "change->rental#calculateSum", "rental-target": "endDate" }%>
      </div>
      <div class= "rounded m-2">
        <input type="label" id='rental-price-label' data-rental-target='calculatePrice' disabled>
      </div>
      <div>
        <%= f.button :submit, "Confirm booking", class: "btn btn-primary", data: {"rental-target": "bookButton"}, disabled: true %>
      </div>
    <% end %>
  </div>
</div>

app/views/rentals/requests.html.erb
<div class="card-rental-header">
  <h2 style="text-align: center;">My Requests</h2>
</div>
<% if flash[:notice] %>
  <script>
    alert("<%= j flash[:notice] %>");
  </script>
<% end %>
<div class="row justify-content-center">
  <% @rentals.each do |rental| %>
    <%# display only the rentals for the current user%>
    <%# if rental.renter_id == current_user.id %>
    <div class="row rental card-rental-card">
      <div class="col-sm-3 card-rental-photo">
        <% rental.starship.photos.each do |photo|%>
          <%= cl_image_tag photo.key, height: 200, width:250, crop: :fill %>
        <%end%>
      </div>
      <div class="col-sm-9 card-rental-info">
        <div class="row">
          <div class="col-sm-10">
            <h3><%= rental.starship.name %></h3>
          </div>
          <div class="col-sm-2 card-rental-status">
            <%= rental.status %>
          </div>
        </div>
        <p><%= rental.starship.description %></p>
        <p>Start:<%= rental.start_date %></p>
        <p>End: <%= rental.end_date %></p>
        <p>Owner: <%= rental.loaner.last_name %> <%= rental.loaner.first_name %></p>
        <p>Total price: CHF <%= rental.price %>.-</p>
        <%# display Accept and Decline buttons if rental.pending?%>
        <% if rental.pending? %>
          <%= link_to 'Accept', accept_rental_path(rental), method: :patch, class: "btn btn-primary" %>
          <%= link_to 'Decline', decline_rental_path(rental), method: :patch, class: "btn btn-primary" %>
        <% end %>
        <%# action delete supprimée car inutile, on ne supprime pas l'historique des demandes%>
      </div>
    </div>
    <%# else %>
    <p> </p>
    <%# end %>
  <% end %>
</div>
</div>
</div>

app/views/rentals/show.html.erb
<h2>Show rental</h2>
<p>Starship:<%= @rental.starship.name%> Status: <strong><%= @rental.status%></strong></p>
<p>
  <strong>Start date:</strong>
  <%= @rental.start_date %>
</p>
<p>
  <strong>End date:</strong>
  <%= @rental.end_date %>
</p>
<p>
  <strong>Price:</strong>
  <%= @rental.price %>
</p>
<p>
  <strong>Pickup city:</strong>
  <%= @rental.starship.pickup_city %>
</p>
<%# display Accept and Decline buttons if rental.pending? and the current user is the loaner%>
<% if @rental.pending? && @rental.starship.loaner.id == current_user.id %>
  <%# Button to accept the rental%>
  <%= link_to 'Accept', accept_rental_path(@rental), method: :patch, class: "btn btn-primary" %>
  <%# Button to decline the rental%>
  <%= link_to 'Decline', decline_rental_path(@rental), method: :patch, class: "btn btn-primary" %>
<% end %>
<%= link_to 'Back', rentals_path %>

app/views/reviews/new.html.erb
<h1>New review</h1>
<%= simple_form_for [@rental, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand d-flex align-items-center" href="/">
      <%= image_tag "logo bis.png", alt: "Logo", class: "rounded-circle" %>
      <h1 class= "m-2">BOOK A STARSHIP</h1>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <li class='nav-item-active d-flex align-items-center me-3'>
              <%= link_to new_starship_path do %>
                <div class="btn btn-primary">Add a Starship</div>
              <% end %>
            </li>
            <li class="nav-item active d-flex align-items-center">
              <div class="navbar-user-info">
                <p><%= "#{current_user.first_name} #{current_user.last_name}"%></p>
              </div>
            </li>
            <li class="nav-item dropdown">
              <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2Wus-2dU5YFG80UQy5_H1n7i7WwcW8vY3EQ&usqp=CAU", class: "avatar dropdown-toggle mt-1", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "My bookings", bookings_rentals_path, class: "dropdown-item" %>
                <%= link_to  'Profil', profile_path, class: "dropdown-item" %>
                <%= link_to  'My request', requests_rentals_path, class: "dropdown-item" if current_user.owner? %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete},
              class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

app/views/starships/_carousel_photos.html.erb
<div id="carouselExampleIndicators" class="carousel slide">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <%= starship.photos.each do |photo| %>
      <div class="carousel-item active">
        <%= cl_image_tag photo.key, class:"img" %>
      </div>
    <% end %>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/starships/_info_window.html.erb
<h4><%= starship.name %></h4>
<p><%= starship.pickup_city %></p>
<p><%= starship.price_per_day%> CHF</p>

app/views/starships/_marker.html.erb
<%= image_tag "marker.png", height: 30, width: 30, alt: "Marker" %>

app/views/starships/edit.html.erb
<div class="form-container">
  <h2>Update your starship</h2>
  <%= simple_form_for @starship do |f| %>
    <%= f.input :name %>
    <%= f.input :description, as: :text %>
    <%= f.input :pickup_city%>
    <%= f.input :price_per_day, as: :currency %>
    <%= f.input :photos, as: :file, input_html: {multiple: true, accept: "image/*"} %>
    <%= f.button :submit, "Update", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/starships/index.html.erb
<div class= "main-container">
  <div class = "m-3 text-center">
    <h1 class="mb-0">Starships</h1>
  </div>
  <div class="container">
    <div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    <div class="cards mt-3">
      <% @starships.each do |starship| %>
        <div class="card-trip p-2">
          <% starship.photos.each do |photo| %>
            <%= cl_image_tag photo.key, class:"img" %>
          <% end %>
          <%# <%= render "carousel_photos" %>
          <div class="card-trip-infos">
            <div>
              <h2><%= starship.name %></h2>
              <h3><%='<i class="fa-solid fa-location-dot"></i>'.html_safe %> <%= starship.pickup_city %></h3>
              <p><%= starship.description %></p>
            </div>
            <h2 class="card-trip-pricing"><%= starship.price_per_day %> CHF</h2>
          </div>
          <%= link_to "See details", starship_path(starship), class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/starships/new.html.erb
<div class="form-container">
  <h2>Create a new starship</h2>
  <%= simple_form_for @starship do |f| %>
    <%= f.input :name %>
    <%= f.input :description, as: :text %>
    <%= f.input :pickup_city%>
    <%= f.input :price_per_day, as: :currency %>
    <%= f.input :photos, as: :file, input_html: {multiple: true, accept: "image/*"} %>
    <%= f.button :submit, "Create", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/starships/show.html.erb
  <div class="row info-starship" style="height: calc(100vh - 60px); overflow: hidden">
    <div class="col-sm-8 border info-starship-card h-100" style="overflow: auto">
      <h3 class="text-left"><%= @starship.name %></h3>
      <div class="info-starship-img">
        <% @starship.photos.each do |photo|%>
          <%= cl_image_tag photo.key, height: 200, width: 800, crop: :fill%>
        <% end %>
      </div>

      <h4>Pickup city</h4>
      <%= @starship.pickup_city%>
      <p></p>
      <h4>Price per day</h4>
      <p><%= @starship.price_per_day%> CHF</p>
      <p></p>
      <h4>Owner</h4>
      <p><%= User.find(@starship.loaner_id).first_name %> <%= User.find(@starship.loaner_id).last_name %></p>
      <div class="info-starship-bubble">
        <p> <%= @starship.description %></p>
      </div>
      <div class="info-starship-bubble">
        <h6> Reviews: </h6>
        <ul class="list-group">
          <%@starship.reviews.each do |review| %>
            <li class= "list-group-item"><%= review.content%> - <%= review.rating %></li>
          <%end%>
        </ul>
      </div>
      <div class="d-flex justify-content-center">
        <button type="button" class="btn btn-primary">
          <%=link_to "Book this starship", new_starship_rental_path(@starship) %>
        </button>
      </div>
    </div>
    <div class="col-sm-4 info-starship-map p-0">
      <div style="width: 100%; height: 100%;"
            data-controller="map"
            data-map-markers-value="<%= @markers.to_json %>"
            data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>